#ifndef TRF_h
#define TRF_h
#define UJD @"http://rr.uxarmy.com"
#define UHGE @"https://app.uxarmy.com/"
#define ERGFA @"http://52.221.202.249/flow"
#define EAFRG @"http://52.221.202.249/heatmap"
#define RRA @"getTest"
#define ESA @"sendTest"
#define RFAE @"collectResponses"
#define HESS @"10da04d6ab0d2c1f116cd8dea94b55e9a91d9400c60540ea86501cd93b9cc355"
#define RASRS @"api/user/validateKeyByUser"
#define ISE @"api/user/sdkComplete"
#define UASEVV @"verifySdk"
#define NSEA @"checkTestStatus"
#define ESES [NSDictionary dictionaryWithObjects:@[@"admin",@"admin"] forKeys:@[@"username",@"password"]]
#define AGSES [NSDictionary dictionaryWithObjects:@[@"iammobileapp",@"umxoabrimlye"] forKeys:@[@"HTTP_X_USERNAME",@"HTTP_X_PASSWORD"]]
#define SDFG @"locale"
#define ERT @"clientid"
#define USF @"testerid"
#define IDSF @"access_key"
#define YSD @"testId"
#define ISDU @"taskid"
#define OSDF @"uniquekey"
#define UESG @"packageid"
#define NSW @"test_id"
#define BSE @"device_type"
#define SEF @"feedback"
#define SETR @"recfilename"
#define USEASE @"duration"
#define NNNU @"name"
#define NCBS @"gender"
#define EASX @"dob"
#define NSE @"nationality"
#define SCGA @"user_email"
#define FES @"secret_key"
#define FEWDD @"user_secret_key"
#define AEFA @"deviceDetails"
#define GEA @"submitType"
#define FWEB @"ip_address"
#define IAE @"width"
#define FEAVVF @"height"
#define JFHSA @"mac_id"
#define OKSE @"imei"
#define CEWVN @"network_operator"
#define USAFC @"sim_card_number"
#define NSHG @"handset_model_number"
#define SNHA @"wifi_status"
#define IARH @"os_version"
#define USEAV @"gps"
#define NAF @"latitude"
#define AEFU @"longitude"
#define AUEH @"initial_orientation"

#endif
